name: "Rotate Daily"


on:
  workflow_dispatch:
    inputs:

  schedule:
    - cron: '3 22 * * *' # Every day at 3:22 AM UTC


jobs:
  rotate-suffix:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    steps:
      - name: Create GitHub App Token
        id: app_token
        uses: actions/create-github-app-token@v3
        with:
          app-id: ${{ secrets.DYSTOPIANBOT_APP_ID }}
          private-key: ${{ secrets.DYSTOPIANBOT_KEY }}
          permission-secrets: write
          permission-organization-secrets: write
          owner: ${{ github.repository_owner }}

      - name: Update Key Suffix
        id: update_suffix
        shell: bash
        env:
          GH_TOKEN: ${{ steps.app_token.outputs.token }}
        run: |
          tr -dc 'A-Z0-9' </dev/urandom | head -c 8 | \
            gh secret set "KEY_SUFFIX" \
                      --org ${{ github.repository_owner }} \
                      --repos ${{ github.repository }},${{ secrets.AUR_DB_REPO_NAME }},${{ secrets.AUR_PKGBUILDS_REPO_NAME }} 
                      --visibility "selected" || {
              echo "::error::Failed to set KEY_SUFFIX secret" >&2
              exit 1
            }

  rotate:
    runs-on: ubuntu-latest
    needs: rotate-suffix
    permissions:
      contents: write
      actions: write
    steps:
      - name: Create GitHub App Token
        id: app_token
        uses: actions/create-github-app-token@v3
        with:
          app-id: ${{ secrets.DYSTOPIANBOT_APP_ID }}
          private-key: ${{ secrets.DYSTOPIANBOT_KEY }}
          permission-secrets: write
          permission-organization-secrets: write
          owner: ${{ github.repository_owner }}

      - name: New Key
        id: new_key
        shell: bash
        env:
          GH_TOKEN: ${{ steps.app_token.outputs.token }}
        run: |
          KEY_NAMES=(
            "${{ format('RANDOM_KEY_{0}0', secrets.KEY_SUFFIX || 'XXX') }}"
            "${{ inputs.key_name || format('RANDOM_KEY_{0}1', secrets.KEY_SUFFIX || 'XXX') }}"
            "###${{ inputs.key_name || format('RANDOM_KEY_{0}2', secrets.KEY_SUFFIX || 'XXX') }}###"
          )

          while LFS= read -r keyname; do
            [ -z "$keyname" ] && continue
            [[ ! "$keyname" =~ ^\#\#\#.*\#\#\#$ ]] && continue || { keyname=$(printf '%s' "$keyname" | sed -e 's/\#\#\#//g') && l=32 ;}
            tr -dc 'A-Za-z0-9!%&()*+,-.:;<=>?@[]' </dev/urandom | head -c ${l:-64} | \
              gh secret set "$keyname" \
                        --org ${{ github.repository_owner }} \
                        --repos ${{ github.repository }},${{ secrets.AUR_DB_REPO_NAME }},${{ secrets.AUR_PKGBUILDS_REPO_NAME }} 
                        --visibility "selected" || {
                echo "::error::Failed to set new key as secret" >&2
                exit 1
              }
          done <<< "${KEY_NAMES[@]}"
          
          echo "New key(s) set successfully: ${KEY_NAMES[*]}" | sed -e 's/\#\#\#//g'
